/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <malloc.h>
#include "rtmp.h"
#include <android/log.h>
#include <stddef.h>
#include <unistd.h>
#include "xiecc_rtmp.h"
/* Header for class org_openlive_android_rtmp_RtmpClient */
#define TYPE_VIDEO 0
#define TYPE_AUDIO 1

#define  LOG_TAG    "librtmp"
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

#ifndef _Included_org_openlive_android_rtmp_RtmpClient
#define _Included_org_openlive_android_rtmp_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    open
 * Signature: (Ljava/lang/String;ZII)I
 */
JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_open(
		JNIEnv * env, jclass obj, jstring _url, jboolean _publishmode,
		jint width, jint height) {

	const char *url = (*env)->GetStringUTFChars(env, _url, 0);
	int result = rtmp_open_for_write(url, width, height);
	(*env)->ReleaseStringUTFChars(env, _url, url);
	return result;
}

/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_read(
		JNIEnv *env, jclass obj, jbyteArray _data, jint offset, jint size) {

	char* data = malloc(size * sizeof(char));

	int readCount = rtmp_read_date(data, size);

	if (readCount > 0) {
		(*env)->SetByteArrayRegion(env, _data, offset, readCount, data); // copy
	}
	free(data);

	return readCount;
}

/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    write
 * Signature: ([BIII)I
 */

JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_write(
		JNIEnv *env, jclass obj, jbyteArray _data, jint size, jint type,
		jint ts) {
	jbyte *data = (*env)->GetByteArrayElements(env, _data, NULL);
	jint result = -1;
	if (type == TYPE_VIDEO) {
		//video
		result = rtmp_sender_write_video_frame(data, size, ts, 0, 0);
	} else if (type == TYPE_AUDIO) {
		//audio
		result = rtmp_sender_write_audio_frame(data, size, ts, 0);
	}

	(*env)->ReleaseByteArrayElements(env, _data, data, 0);
	return result;
}

/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_close(
		JNIEnv *env, jclass obj) {
	rtmp_close();
	return 0;
}

#ifdef __cplusplus
}
#endif
#endif
