/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openlive_android_rtmp_RtmpClient */

#ifndef _Included_org_openlive_android_rtmp_RtmpClient
#define _Included_org_openlive_android_rtmp_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    open
 * Signature: (Ljava/lang/String;ZII)I
 */
JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_open
  (JNIEnv *, jclass, jstring, jboolean, jint, jint);

/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_read
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    write
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_write
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     org_openlive_android_rtmp_RtmpClient
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openlive_android_rtmp_RtmpClient_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
